// @ts-nocheck
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect, useLayoutEffect, useRef } from "react";
import gsap from "gsap";
import * as THREE from "three";

export default function Band_1({
  position,
  rotationStart,
  rotationEnd,
  checkPath,
  scale,
}: any) {
  const { scene, animations } = useGLTF(
    "./RTFA/Models/Band_1/band_1_animated.glb",
    true
  );
  const { ref, mixer } = useAnimations(animations);
  const actionsRef = useRef([]);

  useEffect(() => {
    if (animations && animations.length > 0) {
      animations.forEach((clip, i) => {
        setTimeout(() => {
          const action = mixer.clipAction(clip, ref.current);
          action.play();
          actionsRef.current.push(action);
        }, 10 * i);
      });

      return () =>
        actionsRef.current.forEach((action) => {
          action.stop();
          mixer.uncacheAction(action);
        });
    }
  }, [mixer, animations]);

  return (
    <mesh scale={scale} position={position} rotation={rotationStart}>
      <primitive object={scene} ref={ref} />
    </mesh>
  );
}

useGLTF.preload("/band_1_animated.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
// import { Float, useGLTF, useAnimations } from "@react-three/drei";

// export default function Band_1({
//   position,
//   rotationStart,
//   rotationEnd,
//   checkPath,
//   scale,
// }: any) {
//   const group = useRef();
//   const { nodes, materials, animations } = useGLTF(
//     "./RTFA/Models/Band_1/band_1_animated.glb"
//   );
//   const { actions } = useAnimations(animations, group);
//   return (
//     <group dispose={null}>

//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube.geometry}
//           material={materials["Material.002"]}
//           position={[-14.929, 3.044, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube001.geometry}
//           material={materials["Material.002"]}
//           position={[-15.534, 2.773, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube002.geometry}
//           material={materials["Material.002"]}
//           position={[-16.745, 2.251, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube003.geometry}
//           material={materials["Material.002"]}
//           position={[-16.14, 2.508, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube004.geometry}
//           material={materials["Material.002"]}
//           position={[-18.551, 1.542, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube005.geometry}
//           material={materials["Material.002"]}
//           position={[-19.156, 1.328, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube006.geometry}
//           material={materials["Material.002"]}
//           position={[-17.946, 1.769, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube007.geometry}
//           material={materials["Material.002"]}
//           position={[-17.34, 2.007, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube008.geometry}
//           material={materials["Material.002"]}
//           position={[-12.461, 4.189, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube009.geometry}
//           material={materials["Material.002"]}
//           position={[-13.067, 3.905, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube010.geometry}
//           material={materials["Material.002"]}
//           position={[-14.277, 3.342, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube011.geometry}
//           material={materials["Material.002"]}
//           position={[-13.672, 3.623, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube012.geometry}
//           material={materials["Material.002"]}
//           position={[-11.261, 4.751, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube013.geometry}
//           material={materials["Material.002"]}
//           position={[-11.866, 4.468, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube014.geometry}
//           material={materials["Material.002"]}
//           position={[-10.655, 5.031, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube015.geometry}
//           material={materials["Material.002"]}
//           position={[-10.05, 5.307, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube016.geometry}
//           material={materials["Material.002"]}
//           position={[-19.826, 1.107, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube017.geometry}
//           material={materials["Material.002"]}
//           position={[-20.431, 0.924, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube018.geometry}
//           material={materials["Material.002"]}
//           position={[-21.642, 0.609, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube019.geometry}
//           material={materials["Material.002"]}
//           position={[-21.037, 0.757, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020.geometry}
//           material={materials["Material.002"]}
//           position={[-23.448, 0.285, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube021.geometry}
//           material={materials["Material.002"]}
//           position={[-24.053, 0.22, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube022.geometry}
//           material={materials["Material.002"]}
//           position={[-22.843, 0.372, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube023.geometry}
//           material={materials["Material.002"]}
//           position={[-22.237, 0.481, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube024.geometry}
//           material={materials["Material.002"]}
//           position={[-27.116, 0.165, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube025.geometry}
//           material={materials["Material.002"]}
//           position={[-27.722, 0.165, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube026.geometry}
//           material={materials["Material.002"]}
//           position={[-28.932, 0.165, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube027.geometry}
//           material={materials["Material.002"]}
//           position={[-28.327, 0.165, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube028.geometry}
//           material={materials["Material.002"]}
//           position={[-25.916, 0.165, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube029.geometry}
//           material={materials["Material.002"]}
//           position={[-26.521, 0.165, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube030.geometry}
//           material={materials["Material.002"]}
//           position={[-25.31, 0.165, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube031.geometry}
//           material={materials["Material.002"]}
//           position={[-24.705, 0.178, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube032.geometry}
//           material={materials["Material.002"]}
//           position={[-5.134, 7.244, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube033.geometry}
//           material={materials["Material.002"]}
//           position={[-5.739, 7.047, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube034.geometry}
//           material={materials["Material.002"]}
//           position={[-6.95, 6.611, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube035.geometry}
//           material={materials["Material.002"]}
//           position={[-6.345, 6.835, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube036.geometry}
//           material={materials["Material.002"]}
//           position={[-8.756, 5.878, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube037.geometry}
//           material={materials["Material.002"]}
//           position={[-9.361, 5.614, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube038.geometry}
//           material={materials["Material.002"]}
//           position={[-8.151, 6.133, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube039.geometry}
//           material={materials["Material.002"]}
//           position={[-7.545, 6.379, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube040.geometry}
//           material={materials["Material.002"]}
//           position={[-2.666, 7.877, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube041.geometry}
//           material={materials["Material.002"]}
//           position={[-3.272, 7.75, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube042.geometry}
//           material={materials["Material.002"]}
//           position={[-4.482, 7.439, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube043.geometry}
//           material={materials["Material.002"]}
//           position={[-3.877, 7.603, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube044.geometry}
//           material={materials["Material.002"]}
//           position={[-1.466, 8.068, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube045.geometry}
//           material={materials["Material.002"]}
//           position={[-2.071, 7.983, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube046.geometry}
//           material={materials["Material.002"]}
//           position={[-0.86, 8.129, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube047.geometry}
//           material={materials["Material.002"]}
//           position={[-0.255, 8.165, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube049.geometry}
//           material={materials["Material.002"]}
//           position={[28.333, 0.165, -0.138]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube050.geometry}
//           material={materials["Material.002"]}
//           position={[27.123, 0.165, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube051.geometry}
//           material={materials["Material.002"]}
//           position={[27.728, 0.165, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube052.geometry}
//           material={materials["Material.002"]}
//           position={[25.317, 0.169, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube053.geometry}
//           material={materials["Material.002"]}
//           position={[24.711, 0.195, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube054.geometry}
//           material={materials["Material.002"]}
//           position={[25.922, 0.165, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube055.geometry}
//           material={materials["Material.002"]}
//           position={[26.527, 0.165, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube056.geometry}
//           material={materials["Material.002"]}
//           position={[21.648, 0.686, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube057.geometry}
//           material={materials["Material.002"]}
//           position={[21.043, 0.844, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube058.geometry}
//           material={materials["Material.002"]}
//           position={[19.832, 1.211, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube059.geometry}
//           material={materials["Material.002"]}
//           position={[20.438, 1.02, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube060.geometry}
//           material={materials["Material.002"]}
//           position={[22.849, 0.428, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube061.geometry}
//           material={materials["Material.002"]}
//           position={[22.244, 0.548, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube062.geometry}
//           material={materials["Material.002"]}
//           position={[23.454, 0.329, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube063.geometry}
//           material={materials["Material.002"]}
//           position={[24.059, 0.252, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube064.geometry}
//           material={materials["Material.002"]}
//           position={[4.488, 7.53, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube065.geometry}
//           material={materials["Material.002"]}
//           position={[3.883, 7.685, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube066.geometry}
//           material={materials["Material.002"]}
//           position={[2.673, 7.939, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube067.geometry}
//           material={materials["Material.002"]}
//           position={[3.278, 7.822, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube068.geometry}
//           material={materials["Material.002"]}
//           position={[0.867, 8.152, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube069.geometry}
//           material={materials["Material.002"]}
//           position={[0.261, 8.174, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube070.geometry}
//           material={materials["Material.002"]}
//           position={[1.472, 8.104, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube071.geometry}
//           material={materials["Material.002"]}
//           position={[2.077, 8.032, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube072.geometry}
//           material={materials["Material.002"]}
//           position={[6.956, 6.732, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube073.geometry}
//           material={materials["Material.002"]}
//           position={[6.351, 6.95, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube074.geometry}
//           material={materials["Material.002"]}
//           position={[5.14, 7.343, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube075.geometry}
//           material={materials["Material.002"]}
//           position={[5.746, 7.154, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube076.geometry}
//           material={materials["Material.002"]}
//           position={[8.157, 6.266, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube077.geometry}
//           material={materials["Material.002"]}
//           position={[7.552, 6.507, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube078.geometry}
//           material={materials["Material.002"]}
//           position={[8.762, 6.015, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube079.geometry}
//           material={materials["Material.002"]}
//           position={[9.367, 5.756, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube080.geometry}
//           material={materials["Material.002"]}
//           position={[19.144, 1.447, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube081.geometry}
//           material={materials["Material.002"]}
//           position={[18.538, 1.668, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube082.geometry}
//           material={materials["Material.002"]}
//           position={[17.328, 2.146, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube083.geometry}
//           material={materials["Material.002"]}
//           position={[17.933, 1.902, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube084.geometry}
//           material={materials["Material.002"]}
//           position={[15.522, 2.926, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube085.geometry}
//           material={materials["Material.002"]}
//           position={[14.917, 3.2, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube086.geometry}
//           material={materials["Material.002"]}
//           position={[16.127, 2.657, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube087.geometry}
//           material={materials["Material.002"]}
//           position={[16.732, 2.395, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube088.geometry}
//           material={materials["Material.002"]}
//           position={[11.853, 4.628, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube089.geometry}
//           material={materials["Material.002"]}
//           position={[11.248, 4.909, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube090.geometry}
//           material={materials["Material.002"]}
//           position={[10.038, 5.46, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube091.geometry}
//           material={materials["Material.002"]}
//           position={[10.643, 5.187, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube092.geometry}
//           material={materials["Material.002"]}
//           position={[13.054, 4.066, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube093.geometry}
//           material={materials["Material.002"]}
//           position={[12.449, 4.35, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube094.geometry}
//           material={materials["Material.002"]}
//           position={[13.659, 3.782, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube095.geometry}
//           material={materials["Material.002"]}
//           position={[14.265, 3.5, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />    </group>
//   );
// }

// useGLTF.preload("/band_1_animated.glb");

//@ts-nocheck
// import { useGLTF } from "@react-three/drei";
// import { useEffect, useLayoutEffect, useRef } from "react";
// import gsap from "gsap";

// export default function Band_1({
//   position,
//   rotationStart,
//   rotationEnd,
//   checkPath,
//   scale,
// }: any) {
//   const { nodes, materials } = useGLTF("./RTFA/Models/Band_1/band_1.glb");
//   const meshRef = useRef<any>(null);

//   return (
//     <group dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane.geometry}
//         material={materials["Material.001"]}
//         position={position}
//         rotation={rotationStart}
//         scale={scale}
//         ref={meshRef}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/band_1.glb");
