//@ts-nocheck
// import { useGLTF } from "@react-three/drei";
// import { useEffect, useLayoutEffect, useRef } from "react";
// import gsap from "gsap";

// export default function Band_1({
//   position,
//   rotationStart,
//   rotationEnd,
//   checkPath,
//   scale,
// }: any) {
//   const { nodes, materials } = useGLTF("./RTFA/Models/Band_1/band_1.glb");
//   const meshRef = useRef<any>(null);

//   return (
//     <group dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane.geometry}
//         material={materials["Material.001"]}
//         position={position}
//         rotation={rotationStart}
//         scale={scale}
//         ref={meshRef}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/band_1.glb");

import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect, useLayoutEffect, useRef } from "react";
import gsap from "gsap";
import * as THREE from "three";

export default function Band_1({
  position,
  rotationStart,
  rotationEnd,
  checkPath,
  scale,
}: any) {
  const { scene, animations } = useGLTF(
    "./RTFA/Models/Band_1/band_1_animated.glb",
    true
  );
  const { ref, mixer } = useAnimations(animations);
  const actionsRef = useRef([]);

  useEffect(() => {
    if (animations && animations.length > 0) {
      animations.forEach((clip) => {
        const action = mixer.clipAction(clip, ref.current);
        action.play();
        actionsRef.current.push(action);
      });

      return () =>
        actionsRef.current.forEach((action) => {
          action.stop();
          mixer.uncacheAction(action);
        });
    }
  }, [mixer, animations]);

  return (
    <mesh position={position}>
      <primitive object={scene} ref={ref} />
    </mesh>
  );
}

useGLTF.preload("/band_1_animated.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
// import { Float, useGLTF, useAnimations } from "@react-three/drei";

// export default function Band_1({
//   position,
//   rotationStart,
//   rotationEnd,
//   checkPath,
//   scale,
// }: any) {
//   const group = useRef();
//   const { nodes, materials, animations } = useGLTF(
//     "./RTFA/Models/Band_1/band_1_animated.glb"
//   );
//   const { actions } = useAnimations(animations, group);
//   return (
//     <group ref={group} position={position} dispose={null}>
//       <group name="Scene">
//         <mesh
//           name="Cube"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube.geometry}
//           material={materials["Material.002"]}
//           position={[-14.929, 0.22, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube001"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube001.geometry}
//           material={materials["Material.002"]}
//           position={[-15.534, 0.22, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube002"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube002.geometry}
//           material={materials["Material.002"]}
//           position={[-16.745, 0.22, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube003"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube003.geometry}
//           material={materials["Material.002"]}
//           position={[-16.14, 0.22, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube004"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube004.geometry}
//           material={materials["Material.002"]}
//           position={[-18.551, 0.22, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube005"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube005.geometry}
//           material={materials["Material.002"]}
//           position={[-19.156, 0.22, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube006"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube006.geometry}
//           material={materials["Material.002"]}
//           position={[-17.946, 0.22, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube007"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube007.geometry}
//           material={materials["Material.002"]}
//           position={[-17.34, 0.22, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube008"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube008.geometry}
//           material={materials["Material.002"]}
//           position={[-12.461, 0.22, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube009"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube009.geometry}
//           material={materials["Material.002"]}
//           position={[-13.067, 0.22, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube010"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube010.geometry}
//           material={materials["Material.002"]}
//           position={[-14.277, 0.22, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube011"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube011.geometry}
//           material={materials["Material.002"]}
//           position={[-13.672, 0.22, -0.148]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube012"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube012.geometry}
//           material={materials["Material.002"]}
//           position={[-11.261, 0.22, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube013"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube013.geometry}
//           material={materials["Material.002"]}
//           position={[-11.866, 0.22, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube014"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube014.geometry}
//           material={materials["Material.002"]}
//           position={[-10.655, 0.22, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube015"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube015.geometry}
//           material={materials["Material.002"]}
//           position={[-10.05, 0.22, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube016"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube016.geometry}
//           material={materials["Material.002"]}
//           position={[-19.826, 0.22, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube017"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube017.geometry}
//           material={materials["Material.002"]}
//           position={[-20.431, 0.22, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube018"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube018.geometry}
//           material={materials["Material.002"]}
//           position={[-21.642, 0.22, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube019"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube019.geometry}
//           material={materials["Material.002"]}
//           position={[-21.037, 0.22, -0.149]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube020"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube020.geometry}
//           material={materials["Material.002"]}
//           position={[-23.448, 0.22, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube021"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube021.geometry}
//           material={materials["Material.002"]}
//           position={[-24.053, 0.22, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube022"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube022.geometry}
//           material={materials["Material.002"]}
//           position={[-22.843, 0.22, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube023"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube023.geometry}
//           material={materials["Material.002"]}
//           position={[-22.237, 0.22, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube024"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube024.geometry}
//           material={materials["Material.002"]}
//           position={[-27.116, 0.22, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube025"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube025.geometry}
//           material={materials["Material.002"]}
//           position={[-27.722, 0.22, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube026"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube026.geometry}
//           material={materials["Material.002"]}
//           position={[-28.932, 0.22, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube027"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube027.geometry}
//           material={materials["Material.002"]}
//           position={[-28.327, 0.22, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube028"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube028.geometry}
//           material={materials["Material.002"]}
//           position={[-25.916, 0.22, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube029"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube029.geometry}
//           material={materials["Material.002"]}
//           position={[-26.521, 0.22, -0.151]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube030"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube030.geometry}
//           material={materials["Material.002"]}
//           position={[-25.31, 0.22, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube031"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube031.geometry}
//           material={materials["Material.002"]}
//           position={[-24.705, 0.22, -0.15]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube032"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube032.geometry}
//           material={materials["Material.002"]}
//           position={[-5.134, 0.22, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube033"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube033.geometry}
//           material={materials["Material.002"]}
//           position={[-5.739, 0.22, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube034"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube034.geometry}
//           material={materials["Material.002"]}
//           position={[-6.95, 0.22, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube035"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube035.geometry}
//           material={materials["Material.002"]}
//           position={[-6.345, 0.22, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube036"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube036.geometry}
//           material={materials["Material.002"]}
//           position={[-8.756, 0.22, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube037"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube037.geometry}
//           material={materials["Material.002"]}
//           position={[-9.361, 0.22, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube038"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube038.geometry}
//           material={materials["Material.002"]}
//           position={[-8.151, 0.22, -0.147]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube039"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube039.geometry}
//           material={materials["Material.002"]}
//           position={[-7.545, 0.22, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube040"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube040.geometry}
//           material={materials["Material.002"]}
//           position={[-2.666, 0.22, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube041"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube041.geometry}
//           material={materials["Material.002"]}
//           position={[-3.272, 0.22, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube042"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube042.geometry}
//           material={materials["Material.002"]}
//           position={[-4.482, 0.22, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube043"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube043.geometry}
//           material={materials["Material.002"]}
//           position={[-3.877, 0.22, -0.146]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube044"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube044.geometry}
//           material={materials["Material.002"]}
//           position={[-1.466, 0.22, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube045"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube045.geometry}
//           material={materials["Material.002"]}
//           position={[-2.071, 0.22, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube046"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube046.geometry}
//           material={materials["Material.002"]}
//           position={[-0.86, 0.22, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube047"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube047.geometry}
//           material={materials["Material.002"]}
//           position={[-0.255, 0.22, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube049"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube049.geometry}
//           material={materials["Material.002"]}
//           position={[28.333, 0.22, -0.138]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube050"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube050.geometry}
//           material={materials["Material.002"]}
//           position={[27.123, 0.22, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube051"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube051.geometry}
//           material={materials["Material.002"]}
//           position={[27.728, 0.22, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube052"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube052.geometry}
//           material={materials["Material.002"]}
//           position={[25.317, 0.22, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube053"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube053.geometry}
//           material={materials["Material.002"]}
//           position={[24.711, 0.22, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube054"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube054.geometry}
//           material={materials["Material.002"]}
//           position={[25.922, 0.22, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube055"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube055.geometry}
//           material={materials["Material.002"]}
//           position={[26.527, 0.22, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube056"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube056.geometry}
//           material={materials["Material.002"]}
//           position={[21.648, 0.22, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube057"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube057.geometry}
//           material={materials["Material.002"]}
//           position={[21.043, 0.22, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube058"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube058.geometry}
//           material={materials["Material.002"]}
//           position={[19.832, 0.22, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube059"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube059.geometry}
//           material={materials["Material.002"]}
//           position={[20.438, 0.22, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube060"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube060.geometry}
//           material={materials["Material.002"]}
//           position={[22.849, 0.22, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube061"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube061.geometry}
//           material={materials["Material.002"]}
//           position={[22.244, 0.22, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube062"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube062.geometry}
//           material={materials["Material.002"]}
//           position={[23.454, 0.22, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube063"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube063.geometry}
//           material={materials["Material.002"]}
//           position={[24.059, 0.22, -0.139]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube064"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube064.geometry}
//           material={materials["Material.002"]}
//           position={[4.488, 0.22, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube065"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube065.geometry}
//           material={materials["Material.002"]}
//           position={[3.883, 0.22, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube066"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube066.geometry}
//           material={materials["Material.002"]}
//           position={[2.673, 0.22, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube067"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube067.geometry}
//           material={materials["Material.002"]}
//           position={[3.278, 0.22, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube068"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube068.geometry}
//           material={materials["Material.002"]}
//           position={[0.867, 0.22, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube069"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube069.geometry}
//           material={materials["Material.002"]}
//           position={[0.261, 0.22, -0.145]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube070"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube070.geometry}
//           material={materials["Material.002"]}
//           position={[1.472, 0.22, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube071"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube071.geometry}
//           material={materials["Material.002"]}
//           position={[2.077, 0.22, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube072"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube072.geometry}
//           material={materials["Material.002"]}
//           position={[6.956, 0.22, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube073"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube073.geometry}
//           material={materials["Material.002"]}
//           position={[6.351, 0.22, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube074"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube074.geometry}
//           material={materials["Material.002"]}
//           position={[5.14, 0.22, -0.144]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube075"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube075.geometry}
//           material={materials["Material.002"]}
//           position={[5.746, 0.22, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube076"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube076.geometry}
//           material={materials["Material.002"]}
//           position={[8.157, 0.22, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube077"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube077.geometry}
//           material={materials["Material.002"]}
//           position={[7.552, 0.22, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube078"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube078.geometry}
//           material={materials["Material.002"]}
//           position={[8.762, 0.22, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube079"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube079.geometry}
//           material={materials["Material.002"]}
//           position={[9.367, 0.22, -0.143]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube080"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube080.geometry}
//           material={materials["Material.002"]}
//           position={[19.144, 0.22, -0.14]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube081"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube081.geometry}
//           material={materials["Material.002"]}
//           position={[18.538, 0.22, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube082"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube082.geometry}
//           material={materials["Material.002"]}
//           position={[17.328, 0.22, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube083"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube083.geometry}
//           material={materials["Material.002"]}
//           position={[17.933, 0.22, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube084"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube084.geometry}
//           material={materials["Material.002"]}
//           position={[15.522, 0.22, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube085"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube085.geometry}
//           material={materials["Material.002"]}
//           position={[14.917, 0.22, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube086"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube086.geometry}
//           material={materials["Material.002"]}
//           position={[16.127, 0.22, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube087"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube087.geometry}
//           material={materials["Material.002"]}
//           position={[16.732, 0.22, -0.141]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube088"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube088.geometry}
//           material={materials["Material.002"]}
//           position={[11.853, 0.22, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube089"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube089.geometry}
//           material={materials["Material.002"]}
//           position={[11.248, 0.22, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube090"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube090.geometry}
//           material={materials["Material.002"]}
//           position={[10.038, 0.22, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube091"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube091.geometry}
//           material={materials["Material.002"]}
//           position={[10.643, 0.22, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube092"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube092.geometry}
//           material={materials["Material.002"]}
//           position={[13.054, 0.22, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube093"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube093.geometry}
//           material={materials["Material.002"]}
//           position={[12.449, 0.22, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube094"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube094.geometry}
//           material={materials["Material.002"]}
//           position={[13.659, 0.22, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />

//         <mesh
//           name="Cube095"
//           castShadow
//           receiveShadow
//           geometry={nodes.Cube095.geometry}
//           material={materials["Material.002"]}
//           position={[14.265, 0.22, -0.142]}
//           rotation={[0, -1.57, 0]}
//           scale={[0.1, 13.005, 0.1]}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/band_1_animated.glb");
